// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-portfolio.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-portfolio.ts
var get_portfolio_default = defineTool({
  name: "get_club_portfolio",
  title: "Get club portfolio",
  description: "List EMIL Invest's current holdings with quantity, purchase price and cost basis.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("portfolio_holdings").select("ticker, name, sector, exchange, holding_type, quantity, purchase_price, cost_basis, purchase_date").order("ticker");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { holdings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-performance-history.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var get_performance_history_default = defineTool2({
  name: "get_performance_history",
  title: "Get performance history",
  description: "Daily portfolio value history for EMIL Invest, including the OSEBX benchmark value and invested capital.",
  inputSchema: {
    limit: z.number().int().min(1).max(365).default(60).describe("Number of most recent days to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("portfolio_history").select("date, portfolio_value, osebx_value, invested_capital").order("date", { ascending: false }).limit(limit ?? 60);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).slice().reverse();
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { history: rows }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool3({
  name: "get_competition_leaderboard",
  title: "Get competition leaderboard",
  description: "Ranked results from the latest stock competition leaderboard snapshot.",
  inputSchema: {
    period: z2.enum(["monthly", "yearly", "all_time"]).default("all_time").describe("Which competition period to rank by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ period }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: latest, error: latestError } = await supabase.from("competition_leaderboard").select("snapshot_date").eq("period_type", period ?? "all_time").order("snapshot_date", { ascending: false }).limit(1).maybeSingle();
    if (latestError) return { content: [{ type: "text", text: latestError.message }], isError: true };
    if (!latest) {
      return { content: [{ type: "text", text: "[]" }], structuredContent: { entries: [] } };
    }
    const { data, error } = await supabase.from("competition_leaderboard").select("rank, portfolio_value, return_percentage, snapshot_date, participant_id, competition_participants(display_name)").eq("period_type", period ?? "all_time").eq("snapshot_date", latest.snapshot_date).order("rank", { ascending: true }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-competition-portfolio.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_competition_portfolio_default = defineTool4({
  name: "get_my_competition_portfolio",
  title: "Get my competition portfolio",
  description: "The signed-in user's stock competition participation: holdings, cash (ASK) and recent transactions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: participant, error: pErr } = await supabase.from("competition_participants").select("id, display_name, joined_at, is_active, all_time_start_value, monthly_start_value, yearly_start_value").eq("user_id", ctx.getUserId()).maybeSingle();
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!participant) {
      return {
        content: [{ type: "text", text: "You are not registered in the stock competition." }],
        structuredContent: { participant: null, holdings: [], transactions: [] }
      };
    }
    const [{ data: holdings, error: hErr }, { data: transactions, error: tErr }] = await Promise.all([
      supabase.from("competition_portfolios").select("ticker, quantity, average_purchase_price").eq("participant_id", participant.id),
      supabase.from("competition_transactions").select("ticker, transaction_type, quantity, price_per_share, total_amount, executed_at").eq("participant_id", participant.id).order("executed_at", { ascending: false }).limit(25)
    ]);
    const error = hErr ?? tErr;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { participant, holdings: holdings ?? [], transactions: transactions ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-tradable-stocks.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_tradable_stocks_default = defineTool5({
  name: "list_tradable_stocks",
  title: "List tradable stocks",
  description: "The stocks available for trading in the EMIL Invest stock competition.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("oslo_stocks").select("ticker, name, sector, exchange").eq("is_active", true).order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { stocks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rdiansdvvwkpujidyzoe";
var mcp_default = defineMcp({
  name: "emil-invest",
  title: "Emil Invest",
  version: "0.1.0",
  instructions: "Tools for EMIL Invest, a student investment club at NTNU. Read the club's transparent portfolio and its performance versus the OSEBX benchmark, list stocks tradable in the stock competition, view the competition leaderboard, and read the signed-in user's own competition portfolio and trades. All data is read-only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_portfolio_default,
    get_performance_history_default,
    list_tradable_stocks_default,
    get_leaderboard_default,
    get_my_competition_portfolio_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
